[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# gitを便利に使う
# ステータス行に現在のgitブランチを表示する 	
[[plugins]]
repo = 'tpope/vim-fugitive'

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

# プロジェクトツリーを表示する
[[plugins]]
repo = 'scrooloose/nerdtree'

# 自分用チートシートを表示する(:Cheat)
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# 連番作成
[[plugins]]
repo = 'deris/vim-rengbang'

# フォーマット
[[plugins]]
repo = 'h1mesuke/vim-alignta'

