[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo    = 'tpope/vim-fugitive'

[[plugins]]
repo    = 'tomtom/tcomment_vim'

[[plugins]]
repo    = 'terryma/vim-multiple-cursors'
hook_add = '''
  let g:multi_cursor_select_all_key      = '<f2>'
'''

[[plugins]]
repo    = 'deris/vim-rengbang'

[[plugins]]
repo    = 'h1mesuke/vim-alignta'

[[plugins]]
repo    = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1 
  let g:airline_theme = 'papercolor'
'''
